### ISSUE TITLE
NextJS: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by 404-html** [gluestack/gluestack-ui-themed-native-base#36]
### Description

Next app is throwing an error after 

### Steps to reproduce

1. Clone following repository: https://github.com/404-html/gs-nb-next.git
2. `yarn`
3. `yarn dev`
4. Go to: http://127.0.0.1:3000/

### gluestack-ui Version

@gluestack-ui/themed-native-base: 0.1.104

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [X] Next

### Additional Information

Thanks for the drop-in replacement, great idea.

I followed the instructions, and when running the app, following gets thrown:
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at PagesManifestPlugin.createAssets (path/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:39:47)
    at path/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:61:22
    at fn (path/node_modules/next/dist/compiled/webpack/bundle5.js:22773:10)
    at Hook.eval [as callAsync] (eval at create (path/node_modules/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (path/node_modules/next/dist/compiled/webpack/bundle5.js:140148:14)
    at cont (path/node_modules/next/dist/compiled/webpack/bundle5.js:25351:34)
    at path/node_modules/next/dist/compiled/webpack/bundle5.js:25399:10
    at symbolIterator (path/node_modules/next/dist/compiled/neo-async/async.js:1:14443)
    at done (path/node_modules/next/dist/compiled/neo-async/async.js:1:14823)
    at path/node_modules/next/dist/compiled/neo-async/async.js:1:9429
error - HookWebpackError: Cannot read properties of undefined (reading 'replace')
```

**Comment by akash3gtm** [comment]
hi @404-html, thank you for reporting the issue, we will look into the issue.

**Comment by akash3gtm** [comment]
hi @404-html, thank you for reporting the issue, we will look into it.

**Comment by 404-html** [comment]
> hi @404-html, thank you for reporting the issue, we will look into it.

Thanks. To make things easier, I created a Codesandbox: https://codesandbox.io/p/devbox/ywgl3t

**Comment by akash3gtm** [comment]
hi @404-html , if it is possible can you give me this code-base originally working with `native-base`. so I could provide you step by step instructions on how to migrate properly and find exactly what the issue is?

**Comment by 404-html** [comment]
> hi @404-html , if it is possible can you give me this code-base originally working with `native-base`. so I could provide you step by step instructions on how to migrate properly and find exactly what the issue is?

@akash3gtm sure, there you go: https://github.com/404-html/gs-nb-next/tree/native-base

**Comment by 404-html** [comment]
@akash3gtm do you have any ideas how to make that working?

**Comment by akash3gtm** [comment]
hi @404-html , yes we are working on it.
This specific issue was resolved, but we found another issue and so are working to resolve that.
As soon as we are done with it, we will update you.

**Comment by ArtemSharapanyk** [comment]
The same is when go with expo
